/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagesRouteImport } from './routes/stages'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RouteIdRouteImport } from './routes/route.$id'

const StagesRoute = StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteIdRoute = RouteIdRouteImport.update({
  id: '/route/$id',
  path: '/route/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/results': typeof ResultsRoute
  '/routes': typeof RoutesRoute
  '/stages': typeof StagesRoute
  '/route/$id': typeof RouteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/results': typeof ResultsRoute
  '/routes': typeof RoutesRoute
  '/stages': typeof StagesRoute
  '/route/$id': typeof RouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/results': typeof ResultsRoute
  '/routes': typeof RoutesRoute
  '/stages': typeof StagesRoute
  '/route/$id': typeof RouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alerts' | '/results' | '/routes' | '/stages' | '/route/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/results' | '/routes' | '/stages' | '/route/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/results'
    | '/routes'
    | '/stages'
    | '/route/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ResultsRoute: typeof ResultsRoute
  RoutesRoute: typeof RoutesRoute
  StagesRoute: typeof StagesRoute
  RouteIdRoute: typeof RouteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stages': {
      id: '/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof StagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/$id': {
      id: '/route/$id'
      path: '/route/$id'
      fullPath: '/route/$id'
      preLoaderRoute: typeof RouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ResultsRoute: ResultsRoute,
  RoutesRoute: RoutesRoute,
  StagesRoute: StagesRoute,
  RouteIdRoute: RouteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
