/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AddVehicleRouteImport } from './routes/add-vehicle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesPlateRouteImport } from './routes/vehicles.$plate'

const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AddVehicleRoute = AddVehicleRouteImport.update({
  id: '/add-vehicle',
  path: '/add-vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesPlateRoute = VehiclesPlateRouteImport.update({
  id: '/vehicles/$plate',
  path: '/vehicles/$plate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/report': typeof ReportRoute
  '/sms': typeof SmsRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/report': typeof ReportRoute
  '/sms': typeof SmsRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/report': typeof ReportRoute
  '/sms': typeof SmsRoute
  '/vehicles/$plate': typeof VehiclesPlateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-vehicle' | '/report' | '/sms' | '/vehicles/$plate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-vehicle' | '/report' | '/sms' | '/vehicles/$plate'
  id:
    | '__root__'
    | '/'
    | '/add-vehicle'
    | '/report'
    | '/sms'
    | '/vehicles/$plate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddVehicleRoute: typeof AddVehicleRoute
  ReportRoute: typeof ReportRoute
  SmsRoute: typeof SmsRoute
  VehiclesPlateRoute: typeof VehiclesPlateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-vehicle': {
      id: '/add-vehicle'
      path: '/add-vehicle'
      fullPath: '/add-vehicle'
      preLoaderRoute: typeof AddVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$plate': {
      id: '/vehicles/$plate'
      path: '/vehicles/$plate'
      fullPath: '/vehicles/$plate'
      preLoaderRoute: typeof VehiclesPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddVehicleRoute: AddVehicleRoute,
  ReportRoute: ReportRoute,
  SmsRoute: SmsRoute,
  VehiclesPlateRoute: VehiclesPlateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
