/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as StagesRouteImport } from './routes/stages'
import { Route as SosRouteImport } from './routes/sos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RidersIndexRouteImport } from './routes/riders.index'
import { Route as RidersIdRouteImport } from './routes/riders.$id'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesRoute = StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidersIndexRoute = RidersIndexRouteImport.update({
  id: '/riders/',
  path: '/riders/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidersIdRoute = RidersIdRouteImport.update({
  id: '/riders/$id',
  path: '/riders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sos': typeof SosRoute
  '/stages': typeof StagesRoute
  '/trips': typeof TripsRoute
  '/riders/$id': typeof RidersIdRoute
  '/riders/': typeof RidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sos': typeof SosRoute
  '/stages': typeof StagesRoute
  '/trips': typeof TripsRoute
  '/riders/$id': typeof RidersIdRoute
  '/riders': typeof RidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sos': typeof SosRoute
  '/stages': typeof StagesRoute
  '/trips': typeof TripsRoute
  '/riders/$id': typeof RidersIdRoute
  '/riders/': typeof RidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sos' | '/stages' | '/trips' | '/riders/$id' | '/riders/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sos' | '/stages' | '/trips' | '/riders/$id' | '/riders'
  id:
    | '__root__'
    | '/'
    | '/sos'
    | '/stages'
    | '/trips'
    | '/riders/$id'
    | '/riders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SosRoute: typeof SosRoute
  StagesRoute: typeof StagesRoute
  TripsRoute: typeof TripsRoute
  RidersIdRoute: typeof RidersIdRoute
  RidersIndexRoute: typeof RidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages': {
      id: '/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof StagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riders/': {
      id: '/riders/'
      path: '/riders'
      fullPath: '/riders/'
      preLoaderRoute: typeof RidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riders/$id': {
      id: '/riders/$id'
      path: '/riders/$id'
      fullPath: '/riders/$id'
      preLoaderRoute: typeof RidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SosRoute: SosRoute,
  StagesRoute: StagesRoute,
  TripsRoute: TripsRoute,
  RidersIdRoute: RidersIdRoute,
  RidersIndexRoute: RidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
